---
- name: Create a directory if it does not exist
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: Enable experimental feature
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
  notify: restart docker
