{
 "title": "App Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UI - Web partition generation time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "web_page_gen_time_sum" }
   ]
  },
  {
   "title": "CRAWLER - Number of Page Processed Bot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "crawler_pages_parsed" }
   ]
  },
  {
   "title": "UI - Number of processed requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "web_pages_served" }
   ]
  },
  {
   "title": "CRAWLER - время затраченное ботом на обработку содержимого веб-страницы",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "crawler_page_parse_time_sum" }
   ]
  },
  {
   "title": "CRAWLER  -  время затраченное ботом на подключение к веб-сайту и загрузку веб-страницы",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_site_connection_time_sum"
    }
   ]
  }
 ]
}